### ISSUE TITLE
Project Plan

### ISSUE THREAD

**Issue by devinschumacher** [serpcompany/operation-sop-street#1]
Lets map out the high-level stages/needs of what this would take.

self hosted runme forks:
- [ ] for the runme main whatever
- [ ] for the cli
- [ ] for the web editor
- [ ] .... all with appropriate app. monitoring

**on github:**
- a github repo or organization to connect to for all the users
- github api scripts for additional features to runme (like our idea of community templates)

**User/account:**
- account signup/login frontend
- connected to our central auth
- email sending
- payments

???
